# Generated by Django 3.0 on 2021-06-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='signup',
        ),
    ]
